#设置语言
language: python

sudo: enabled

#设置相应的版本
python:
  - "2.7"

# 更改时区
before_install:
  - export TZ='Asia/Shanghai'

# command to install dependencies
install:
  - pip install flake8 flake8-respect-noqa pre-commit

# command to run tests
script:
  - python make.py

after_script:
  # GH_REF是最下面配置的仓库地址
  - cd ./
  - git config user.name "Hosiang1026"
  - git config user.email "hosiang1026@sina.com"
  - git init
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"

  # Coding Pages
  - git push --force --quiet "https://Hosiang1026:${CO_TOKEN}@${CO_REF}" master:master
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Taged By TravisCI With Build $TRAVIS_BUILD_NUMBER"


branches:
  only:
    - master

# 配置Webhook通知
notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=efd3fcd86a9e3e8b69c1db1e67284191826be28b775a6e60e7453755a9ae9289
  on_success: change
  on_failure: always
  on_start:   change
  on_cancel:  always
  on_error:   always