#设置语言
language: node_js

#设置相应的版本
node_js: stable

# 缓存不经常更改的内容
cache:
  apt: true
  directories:
    - node_modules

# 更改时区
before_install:
  - export TZ='Asia/Shanghai'

# command to install dependencies
install:
  - npm install

# command to run tests
script:
  - node tool.js

after_script:
  # GH_REF是最下面配置的仓库地址
  - git clone https://${GH_REF} resources
  - cd  resources
  - git checkout master
  - cd ./
  - git config user.name "Hosiang1026"
  - git config user.email "hosiang1026@sina.com"
  - git init
  - git add .
  - git commit -m "Update Photos By TravisCI With Build $TRAVIS_BUILD_NUMBER"

  # Github Pages
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  # Coding Pages
  - git push --force --quiet "https://Hosiang1026:${CO_TOKEN}@${CO_REF}" master:master
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Taged By TravisCI With Build $TRAVIS_BUILD_NUMBER"


branches:
  only:
    - source

# 配置Webhook通知
notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=6d3354513b93c853cd0250984784bd023de87449122f1bbae431e0b9030c81ab
  on_success: change
  on_failure: always
  on_start:   change
  on_cancel:  always
  on_error:   always