#设置语言
language: node_js

#设置相应的版本
node_js: stable

# 更改时区
before_install:
  - export TZ='Asia/Shanghai'

after_script:
  # GH_REF是最下面配置的仓库地址
  - git clone https://github.com/Hosiang1026/photos.git
  - git checkout master
  - cd ../
  - git config user.name "Hosiang1026"
  - git config user.email "hosiang1026@sina.com"
  - git init
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"

  # Coding Pages
  - git push --force --quiet "https://Hosiang1026:${CO_TOKEN}@${CO_REF}" master:master
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Taged By TravisCI With Build $TRAVIS_BUILD_NUMBER"


branches:
  only:
    - master

env:
  global:
    # Coding Pages
    - CO_REF: git.dev.tencent.com/Hosiang1026/Hosiang1026/photos.git




# 配置Webhook通知
notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=efd3fcd86a9e3e8b69c1db1e67284191826be28b775a6e60e7453755a9ae9289
  on_success: change
  on_failure: always
  on_start:   change
  on_cancel:  always
  on_error:   always